// playground/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { MentionInput, version } from 'mentionly'
import type { Part, PopupMode, PopupScrollBehavior, MentionItem, MentionTrigger } from 'mentionly'
import CodeBlock from './components/CodeBlock.vue'
import FloatingSectionIndicator from './components/FloatingSectionIndicator.vue'
import FrameworkSwitch from './components/FrameworkSwitch.vue'
import { detectLocale, alternateLocale } from '@playground/shared/locale'
import { uiStrings, type Locale } from '@playground/shared/i18n'
import { resolveSections } from '@playground/shared/sections'
import {
  parseCustomAtItems,
  createDemoTriggers,
  createCustomTriggerDemo,
  createPaginationTrigger,
  createInsertPayload,
  getSavedParts,
} from '@playground/shared/demo-data'
import { code } from './code'

const inputRef = ref()
const output = ref<Part[]>([])
const popupMode = ref<PopupMode>('cursor')
const popupScrollBehavior = ref<PopupScrollBehavior>('reposition')
const usageBlockEnter = ref(false)
const insertDemoRef = ref()
const insertCount = ref(0)

// ── i18n ──
// 界面文案来自共享层，示例代码来自本应用（Vue 代码片段不进共享层）
const locale = ref<Locale>(detectLocale())

const t = computed(() => ({ ...uiStrings(locale.value), ...code[locale.value] }))

// 右侧浮动 TOC 跟踪的区块（顺序与文档顺序一致；「Deprecated 1.x API」只有 Vue 页有）
const tocSections = computed(() => resolveSections(uiStrings(locale.value), { includeDeprecated: true }))

// 自定义 @ 数据源
const customAtInput = ref('John Smith, Alice Johnson, Michael Brown, Emily Davis, David Wilson')
const customAtItems = computed<MentionItem[]>(() => parseCustomAtItems(customAtInput.value))

const triggers = computed(() =>
  createDemoTriggers(uiStrings(locale.value), customAtItems.value, {
    clear: () => inputRef.value?.clear(),
    help: () => alert(uiStrings(locale.value).helpMsg),
  }),
)

function onSubmit(parts: Part[]) {
  output.value = parts
  console.log('Submit:', parts)
}

function onChange(parts: Part[]) {
  console.log('Change:', parts)
}

function onUsageEnter(e: KeyboardEvent) {
  if (usageBlockEnter.value) e.preventDefault()
}

function onUsageSubmit(parts: Part[]) {
  console.log('Usage submit:', parts)
}

const customTriggerDemo = computed(() => createCustomTriggerDemo(uiStrings(locale.value)))

// 分页（加载更多）演示：模拟一个有大量结果的远程数据源
const paginationDemo: MentionTrigger[] = [createPaginationTrigger()]

function insertContextNode() {
  insertCount.value += 1
  insertDemoRef.value?.insertMention(createInsertPayload(uiStrings(locale.value), insertCount.value))
}

// 反序列化测试
function loadSaved() {
  inputRef.value?.setContent(getSavedParts(locale.value))
}
</script>

<template>
  <div class="playground">
    <div class="header">
      <h1>Mentionly Playground <span class="version">v{{ version }}</span></h1>
      <div class="header-tools">
        <FrameworkSwitch :locale="locale" current="vue" />
        <button class="lang-btn" @click="locale = alternateLocale(locale)">
          {{ locale === 'en' ? '中文' : 'EN' }}
        </button>
      </div>
    </div>
    <div class="header-actions">
      <a class="badge" href="https://github.com/jz0ojiang/mentionly/actions/workflows/test.yml" target="_blank" rel="noreferrer">
        <img src="https://github.com/jz0ojiang/mentionly/actions/workflows/test.yml/badge.svg" alt="tests" />
      </a>
      <a class="badge" href="https://www.npmjs.com/package/mentionly" target="_blank" rel="noreferrer">
        <img src="https://img.shields.io/npm/v/mentionly?color=3b82f6&label=npm&logo=npm" alt="npm version" />
      </a>
      <a class="badge" href="https://www.npmjs.com/package/mentionly" target="_blank" rel="noreferrer">
        <img src="https://img.shields.io/npm/dm/mentionly?color=10b981&label=downloads&logo=npm" alt="npm downloads" />
      </a>
      <a class="badge" href="https://github.com/jz0ojiang/mentionly" target="_blank" rel="noreferrer">
        <img src="https://img.shields.io/badge/GitHub-Repo-111827?logo=github" alt="github repo" />
      </a>
    </div>
    <p class="hint">
      {{ t.hint[0] }}<code>@</code>{{ t.hint[1] }}<code>#</code>{{ t.hint[2] }}<code>/</code>{{ t.hint[3] }}
    </p>

    <section id="sec-config" class="section">
      <h2 class="section-title">Playground</h2>
      <div class="controls">
        <div class="mode-switch">
          <label>
            <span>{{ t.popupMode }}</span>
            <select v-model="popupMode">
              <option value="fixed">{{ t.popupFixed }}</option>
              <option value="cursor">{{ t.popupCursor }}</option>
            </select>
          </label>
        </div>

        <div class="mode-switch">
          <label>
            <span>{{ t.popupScroll }}</span>
            <select v-model="popupScrollBehavior">
              <option value="reposition">{{ t.popupScrollReposition }}</option>
              <option value="close">{{ t.popupScrollClose }}</option>
              <option value="ignore">{{ t.popupScrollIgnore }}</option>
            </select>
          </label>
        </div>

        <div class="custom-at">
          <label>
            <span>{{ t.customAt }}</span>
            <input v-model="customAtInput" class="custom-at-input" />
          </label>
          <p class="custom-at-preview">{{ t.customAtPreview(customAtItems.map(i => i.label).join(locale === 'zh' ? '、' : ', ')) }}</p>
        </div>
      </div>
    </section>

    <section id="sec-editor" class="section">
      <h2 class="section-title">Editor</h2>
      <div class="input-area">
        <MentionInput
          ref="inputRef"
          :triggers="triggers"
          :popup-mode="popupMode"
          :popup-scroll-behavior="popupScrollBehavior"
          :placeholder="t.placeholder"
          @submit="onSubmit"
          @change="onChange"
        >
          <template #inner-actions="{ submit, isEmpty }">
            <div class="inner-actions">
              <button class="send-btn" :disabled="isEmpty" @click="submit">
                {{ t.send }}
              </button>
            </div>
          </template>

          <template #default="{ isEmpty: empty, focus: focusFn }">
            <div class="extra-info">
              <span>{{ empty ? t.waiting : t.editing }}</span>
              <button class="focus-btn" @click="focusFn">{{ t.focusEditor }}</button>
            </div>
          </template>
        </MentionInput>
      </div>

      <div class="actions">
        <button @click="loadSaved">{{ t.loadSaved }}</button>
        <button @click="inputRef?.focus()">{{ t.focus }}</button>
        <button @click="inputRef?.clear()">{{ t.clear }}</button>
      </div>
    </section>

    <section id="sec-output" class="section">
      <h2 class="section-title">Submit Output</h2>
      <div v-if="output.length" class="output">
        <pre>{{ JSON.stringify(output, null, 2) }}</pre>
      </div>
      <div v-else class="output-empty">{{ t.waiting }}</div>
    </section>

    <section class="section">
      <h2 class="section-title">{{ t.usageTitle }}</h2>
      <div class="usage">
        <div id="sec-basic" class="usage-section">
          <div class="usage-header">
            <h4>{{ t.basicTitle }}</h4>
            <p>{{ t.basicDesc }}</p>
          </div>
          <div class="usage-demo">
            <MentionInput
              :triggers="triggers"
              :placeholder="t.placeholder"
              :popup-scroll-behavior="popupScrollBehavior"
              @submit="onUsageSubmit"
            />
          </div>
          <CodeBlock :code="t.basicCode" :copy-label="t.copy" :copied-label="t.copied" />
        </div>

        <div id="sec-custom-trigger" class="usage-section">
          <div class="usage-header">
            <h4>{{ t.customTriggerTitle }}</h4>
            <p>{{ t.customTriggerDesc }}</p>
          </div>
          <div class="usage-demo">
            <MentionInput
              :triggers="customTriggerDemo"
              :placeholder="t.customTriggerPlaceholder"
              :popup-scroll-behavior="popupScrollBehavior"
            />
          </div>
          <CodeBlock :code="t.customTriggerCode" :copy-label="t.copy" :copied-label="t.copied" />
        </div>

        <div id="sec-advanced" class="usage-section">
          <div class="usage-header">
            <h4>{{ t.advancedTitle }}</h4>
            <p>{{ t.advancedDesc }}</p>
          </div>
          <div class="usage-demo">
            <div class="usage-controls">
              <label>
                <input v-model="usageBlockEnter" type="checkbox" />
                <span>{{ t.streaming }}</span>
              </label>
              <p class="streaming-note">{{ t.streamingNote }}</p>
            </div>
            <MentionInput
              :triggers="triggers"
              :placeholder="t.placeholder"
              :popup-scroll-behavior="popupScrollBehavior"
              :on-enter="onUsageEnter"
              @submit="onUsageSubmit"
            >
              <template #inner-actions="{ submit, isEmpty }">
                <div class="inner-actions">
                  <button class="send-btn" :disabled="isEmpty" @click="submit">
                    {{ t.send }}
                  </button>
                </div>
              </template>
            </MentionInput>
          </div>
          <CodeBlock :code="t.advancedCode" :copy-label="t.copy" :copied-label="t.copied" />
        </div>

        <div id="sec-avatar" class="usage-section">
          <div class="usage-header">
            <h4>{{ t.avatarTitle }}</h4>
            <p>{{ t.avatarDesc }}</p>
          </div>
          <div class="usage-demo">
            <MentionInput
              :triggers="triggers"
              :placeholder="t.placeholder"
              :popup-scroll-behavior="popupScrollBehavior"
            >
              <template #item="{ item, active, select }">
                <div class="mention-item" :class="{ active }" @click="select">
                  <span class="avatar">{{ item.label[0] }}</span>
                  <span>{{ item.label }}</span>
                </div>
              </template>
            </MentionInput>
          </div>
          <CodeBlock :code="t.avatarCode" :copy-label="t.copy" :copied-label="t.copied" />
        </div>

        <div id="sec-insert" class="usage-section">
          <div class="usage-header">
            <h4>{{ t.insertTitle }}</h4>
            <p>{{ t.insertDesc }}</p>
          </div>
          <div class="usage-demo">
            <MentionInput
              ref="insertDemoRef"
              :triggers="triggers"
              :placeholder="t.insertPlaceholder"
              :popup-scroll-behavior="popupScrollBehavior"
            />
            <div class="card-actions">
              <button class="card-btn" @click="insertContextNode">{{ t.insertAction }}</button>
            </div>
          </div>
          <CodeBlock :code="t.insertCode" :copy-label="t.copy" :copied-label="t.copied" />
        </div>

        <div id="sec-pagination" class="usage-section">
          <div class="usage-header">
            <h4>{{ t.paginationTitle }}</h4>
            <p>{{ t.paginationDesc }}</p>
          </div>
          <div class="usage-demo">
            <MentionInput
              :triggers="paginationDemo"
              :placeholder="t.paginationPlaceholder"
              :popup-scroll-behavior="popupScrollBehavior"
            />
          </div>
          <CodeBlock :code="t.paginationCode" :copy-label="t.copy" :copied-label="t.copied" />
        </div>

        <div id="sec-deprecated" class="usage-section">
          <div class="usage-header">
            <h4>{{ t.deprecatedTitle }}</h4>
            <p>{{ t.deprecatedDesc }}</p>
          </div>
          <CodeBlock :code="t.deprecatedCode" :copy-label="t.copy" :copied-label="t.copied" />
        </div>
      </div>
    </section>

    <FloatingSectionIndicator :sections="tocSections" />
  </div>
</template>

// examples/react/src/App.tsx
/*
 * Playground 的 React 页面：与 Vue playground/App.vue 的分区、布局、文案、演示数据逐项对应。
 * - 界面文案来自共享层 @playground/shared（i18n.ts），演示数据 / triggers 来自 demo-data.ts
 * - 右侧浮动目录的分区来自 sections.ts（不含 Vue 独有的「Deprecated 1.x API」）
 * - 示例代码来自本应用的 src/code.ts（React 语法）
 */
import { useCallback, useMemo, useRef, useState } from 'react'
import { version } from '@mentionly/react'
import type { MentionTrigger, Part, PopupMode, PopupScrollBehavior } from '@mentionly/react'
import { MentionInput, type MentionInputHandle } from './MentionInput'
import { CodeBlock } from './components/CodeBlock'
import { FloatingSectionIndicator } from './components/FloatingSectionIndicator'
import { FrameworkSwitch } from './components/FrameworkSwitch'
import { detectLocale, alternateLocale } from '@playground/shared/locale'
import { uiStrings, type Locale } from '@playground/shared/i18n'
import { resolveSections } from '@playground/shared/sections'
import {
  parseCustomAtItems,
  createDemoTriggers,
  createCustomTriggerDemo,
  createPaginationTrigger,
  createInsertPayload,
  getSavedParts,
} from '@playground/shared/demo-data'
import { code } from './code'

// 分页（加载更多）演示：模拟一个有大量结果的远程数据源（模块级常量 = 引用稳定）
const paginationDemo: MentionTrigger[] = [createPaginationTrigger()]

const DEFAULT_CUSTOM_AT = 'John Smith, Alice Johnson, Michael Brown, Emily Davis, David Wilson'

export function App() {
  const inputRef = useRef<MentionInputHandle>(null)
  const insertDemoRef = useRef<MentionInputHandle>(null)
  const insertCount = useRef(0)

  const [output, setOutput] = useState<Part[]>([])
  const [popupMode, setPopupMode] = useState<PopupMode>('cursor')
  const [popupScrollBehavior, setPopupScrollBehavior] = useState<PopupScrollBehavior>('reposition')
  const [usageBlockEnter, setUsageBlockEnter] = useState(false)
  const [customAtInput, setCustomAtInput] = useState(DEFAULT_CUSTOM_AT)

  // ── i18n ──
  // 初始语言看 ?lang= / 浏览器语言；切换只改内存状态（与 Vue 版一致），
  // 框架切换链接会带上当前 lang（frameworkHref → withLangParam）
  const [locale, setLocale] = useState<Locale>(() => detectLocale())

  const t = useMemo(() => ({ ...uiStrings(locale), ...code[locale] }), [locale])

  // 右侧浮动 TOC 跟踪的区块（顺序与文档顺序一致；不含 Vue 独有的 Deprecated 分区）
  const tocSections = useMemo(() => resolveSections(uiStrings(locale), { includeDeprecated: false }), [locale])

  // 自定义 @ 数据源
  const customAtItems = useMemo(() => parseCustomAtItems(customAtInput), [customAtInput])

  const triggers = useMemo(
    () =>
      createDemoTriggers(uiStrings(locale), customAtItems, {
        clear: () => inputRef.current?.clear(),
        help: () => alert(uiStrings(locale).helpMsg),
      }),
    [locale, customAtItems],
  )

  const customTriggerDemo = useMemo(() => createCustomTriggerDemo(uiStrings(locale)), [locale])

  const onSubmit = useCallback((parts: Part[]) => {
    setOutput(parts)
    console.log('Submit:', parts)
  }, [])

  const onChange = useCallback((parts: Part[]) => {
    console.log('Change:', parts)
  }, [])

  const onUsageEnter = useCallback(
    (e: KeyboardEvent) => {
      if (usageBlockEnter) e.preventDefault()
    },
    [usageBlockEnter],
  )

  const onUsageSubmit = useCallback((parts: Part[]) => {
    console.log('Usage submit:', parts)
  }, [])

  const insertContextNode = useCallback(() => {
    insertCount.current += 1
    insertDemoRef.current?.insertMention(createInsertPayload(uiStrings(locale), insertCount.current))
  }, [locale])

  // 反序列化测试
  const loadSaved = useCallback(() => {
    inputRef.current?.setContent(getSavedParts(locale))
  }, [locale])

  return (
    <div className="playground">
      <div className="header">
        <h1>
          Mentionly Playground <span className="version">v{version}</span>
        </h1>
        <div className="header-tools">
          <FrameworkSwitch locale={locale} current="react" />
          <button className="lang-btn" onClick={() => setLocale(alternateLocale(locale))}>
            {locale === 'en' ? '中文' : 'EN'}
          </button>
        </div>
      </div>
      <div className="header-actions">
        <a
          className="badge"
          href="https://github.com/jz0ojiang/mentionly/actions/workflows/test.yml"
          target="_blank"
          rel="noreferrer"
        >
          <img src="https://github.com/jz0ojiang/mentionly/actions/workflows/test.yml/badge.svg" alt="tests" />
        </a>
        <a className="badge" href="https://www.npmjs.com/package/mentionly" target="_blank" rel="noreferrer">
          <img src="https://img.shields.io/npm/v/mentionly?color=3b82f6&label=npm&logo=npm" alt="npm version" />
        </a>
        <a className="badge" href="https://www.npmjs.com/package/mentionly" target="_blank" rel="noreferrer">
          <img src="https://img.shields.io/npm/dm/mentionly?color=10b981&label=downloads&logo=npm" alt="npm downloads" />
        </a>
        <a className="badge" href="https://github.com/jz0ojiang/mentionly" target="_blank" rel="noreferrer">
          <img src="https://img.shields.io/badge/GitHub-Repo-111827?logo=github" alt="github repo" />
        </a>
      </div>
      <p className="hint">
        {t.hint[0]}
        <code>@</code>
        {t.hint[1]}
        <code>#</code>
        {t.hint[2]}
        <code>/</code>
        {t.hint[3]}
      </p>

      <section id="sec-config" className="section">
        <h2 className="section-title">Playground</h2>
        <div className="controls">
          <div className="mode-switch">
            <label>
              <span>{t.popupMode}</span>
              <select value={popupMode} onChange={(e) => setPopupMode(e.target.value as PopupMode)}>
                <option value="fixed">{t.popupFixed}</option>
                <option value="cursor">{t.popupCursor}</option>
              </select>
            </label>
          </div>

          <div className="mode-switch">
            <label>
              <span>{t.popupScroll}</span>
              <select
                value={popupScrollBehavior}
                onChange={(e) => setPopupScrollBehavior(e.target.value as PopupScrollBehavior)}
              >
                <option value="reposition">{t.popupScrollReposition}</option>
                <option value="close">{t.popupScrollClose}</option>
                <option value="ignore">{t.popupScrollIgnore}</option>
              </select>
            </label>
          </div>

          <div className="custom-at">
            <label>
              <span>{t.customAt}</span>
              <input
                className="custom-at-input"
                value={customAtInput}
                onChange={(e) => setCustomAtInput(e.target.value)}
              />
            </label>
            <p className="custom-at-preview">
              {t.customAtPreview(customAtItems.map((i) => i.label).join(locale === 'zh' ? '、' : ', '))}
            </p>
          </div>
        </div>
      </section>

      <section id="sec-editor" className="section">
        <h2 className="section-title">Editor</h2>
        <div className="input-area">
          <MentionInput
            ref={inputRef}
            triggers={triggers}
            popupMode={popupMode}
            popupScrollBehavior={popupScrollBehavior}
            placeholder={t.placeholder}
            onSubmit={onSubmit}
            onChange={onChange}
            renderInnerActions={({ submit, isEmpty }) => (
              <div className="inner-actions">
                <button className="send-btn" disabled={isEmpty} onClick={submit}>
                  {t.send}
                </button>
              </div>
            )}
          >
            {({ isEmpty, focus }) => (
              <div className="extra-info">
                <span>{isEmpty ? t.waiting : t.editing}</span>
                <button className="focus-btn" onClick={focus}>
                  {t.focusEditor}
                </button>
              </div>
            )}
          </MentionInput>
        </div>

        <div className="actions">
          <button onClick={loadSaved}>{t.loadSaved}</button>
          <button onClick={() => inputRef.current?.focus()}>{t.focus}</button>
          <button onClick={() => inputRef.current?.clear()}>{t.clear}</button>
        </div>
      </section>

      <section id="sec-output" className="section">
        <h2 className="section-title">Submit Output</h2>
        {output.length ? (
          <div className="output">
            <pre>{JSON.stringify(output, null, 2)}</pre>
          </div>
        ) : (
          <div className="output-empty">{t.waiting}</div>
        )}
      </section>

      <section className="section">
        <h2 className="section-title">{t.usageTitle}</h2>
        <div className="usage">
          <div id="sec-basic" className="usage-section">
            <div className="usage-header">
              <h4>{t.basicTitle}</h4>
              <p>{t.basicDesc}</p>
            </div>
            <div className="usage-demo">
              <MentionInput
                triggers={triggers}
                placeholder={t.placeholder}
                popupScrollBehavior={popupScrollBehavior}
                onSubmit={onUsageSubmit}
              />
            </div>
            <CodeBlock code={t.basicCode} language="tsx" copyLabel={t.copy} copiedLabel={t.copied} />
          </div>

          <div id="sec-custom-trigger" className="usage-section">
            <div className="usage-header">
              <h4>{t.customTriggerTitle}</h4>
              <p>{t.customTriggerDesc}</p>
            </div>
            <div className="usage-demo">
              <MentionInput
                triggers={customTriggerDemo}
                placeholder={t.customTriggerPlaceholder}
                popupScrollBehavior={popupScrollBehavior}
              />
            </div>
            <CodeBlock code={t.customTriggerCode} language="tsx" copyLabel={t.copy} copiedLabel={t.copied} />
          </div>

          <div id="sec-advanced" className="usage-section">
            <div className="usage-header">
              <h4>{t.advancedTitle}</h4>
              <p>{t.advancedDesc}</p>
            </div>
            <div className="usage-demo">
              <div className="usage-controls">
                <label>
                  <input
                    type="checkbox"
                    checked={usageBlockEnter}
                    onChange={(e) => setUsageBlockEnter(e.target.checked)}
                  />
                  <span>{t.streaming}</span>
                </label>
                <p className="streaming-note">{t.streamingNote}</p>
              </div>
              <MentionInput
                triggers={triggers}
                placeholder={t.placeholder}
                popupScrollBehavior={popupScrollBehavior}
                onEnter={onUsageEnter}
                onSubmit={onUsageSubmit}
                renderInnerActions={({ submit, isEmpty }) => (
                  <div className="inner-actions">
                    <button className="send-btn" disabled={isEmpty} onClick={submit}>
                      {t.send}
                    </button>
                  </div>
                )}
              />
            </div>
            <CodeBlock code={t.advancedCode} language="tsx" copyLabel={t.copy} copiedLabel={t.copied} />
          </div>

          <div id="sec-avatar" className="usage-section">
            <div className="usage-header">
              <h4>{t.avatarTitle}</h4>
              <p>{t.avatarDesc}</p>
            </div>
            <div className="usage-demo">
              <MentionInput
                triggers={triggers}
                placeholder={t.placeholder}
                popupScrollBehavior={popupScrollBehavior}
                renderItem={({ item, active, select }) => (
                  <div className={`mention-item${active ? ' active' : ''}`} onClick={select}>
                    <span className="avatar">{item.label[0]}</span>
                    <span>{item.label}</span>
                  </div>
                )}
              />
            </div>
            <CodeBlock code={t.avatarCode} language="tsx" copyLabel={t.copy} copiedLabel={t.copied} />
          </div>

          <div id="sec-insert" className="usage-section">
            <div className="usage-header">
              <h4>{t.insertTitle}</h4>
              <p>{t.insertDesc}</p>
            </div>
            <div className="usage-demo">
              <MentionInput
                ref={insertDemoRef}
                triggers={triggers}
                placeholder={t.insertPlaceholder}
                popupScrollBehavior={popupScrollBehavior}
              />
              <div className="card-actions">
                <button className="card-btn" onClick={insertContextNode}>
                  {t.insertAction}
                </button>
              </div>
            </div>
            <CodeBlock code={t.insertCode} language="tsx" copyLabel={t.copy} copiedLabel={t.copied} />
          </div>

          <div id="sec-pagination" className="usage-section">
            <div className="usage-header">
              <h4>{t.paginationTitle}</h4>
              <p>{t.paginationDesc}</p>
            </div>
            <div className="usage-demo">
              <MentionInput
                triggers={paginationDemo}
                placeholder={t.paginationPlaceholder}
                popupScrollBehavior={popupScrollBehavior}
              />
            </div>
            <CodeBlock code={t.paginationCode} language="tsx" copyLabel={t.copy} copiedLabel={t.copied} />
          </div>
        </div>
      </section>

      <FloatingSectionIndicator sections={tocSections} />
    </div>
  )
}
