// examples/svelte/src/MentionInput.svelte
<script lang="ts">
  /*
   * 一个「可直接复制到自己项目」的完整 mention 输入框（Svelte 5 runes）。
   *
   * 复制方式：把 MentionInput.svelte + MentionInput.css 拷到你的项目
   * （依赖只有 @mentionly/svelte、svelte 本身和这份 CSS）。
   *
   * 三条要点（都来自 @mentionly/core）：
   * 1. 编辑器是空的 contenteditable 元素，用 `use:mention.mention` 交给 core。
   *    ⚠ 不要往这个元素里渲染 Svelte 子节点 —— 内部 DOM（mention span、光标等）由 core 直接管理。
   * 2. 候选列表的 id 必须用 `mention.ids.listbox` / `mention.ids.option(i)`：core 会自动在编辑器上
   *    设置 aria-controls / aria-activedescendant 指向它们，读屏软件才能正确朗读。
   * 3. ↑ ↓ Enter Tab Esc 的键盘导航全部由 core 处理（core 自己绑了 handlers），本组件只补
   *    「列表关闭时 Enter 提交」和自定义操作区。
   *
   * 外观沿用 @mentionly/vue 的类名与样式（MentionInput.css），方便和 Vue 版逐像素对照。
   */
  import { untrack } from 'svelte'
  import type { Snippet } from 'svelte'
  import {
    createMention,
    type InsertMentionOptions,
    type InsertMentionPayload,
    type MentionCoreIds,
    type MentionItem,
    type MentionTrigger,
    type Part,
    type PopupMode,
    type PopupScrollBehavior,
  } from '@mentionly/svelte'
  import './MentionInput.css'

  /** `innerActions` / `actions` 两个 snippet 的作用域参数 */
  interface ActionSlotProps {
    submit: () => void
    clear: () => void
    isEmpty: boolean
  }

  interface MentionInputProps {
    /**
     * 触发器配置。页面里请用稳定引用（模块级常量或 `$derived`）：引用变化会关闭当前列表，
     * 用来实现「换语言 / 换数据源后列表重新加载」。
     */
    triggers: MentionTrigger[]
    placeholder?: string
    disabled?: boolean
    /** 编辑器最大高度，超出滚动 */
    maxHeight?: string
    /** 列表关闭时 Enter 提交（Shift+Enter 换行）。列表打开时 Enter 始终用于选中候选项 */
    submitOnEnter?: boolean
    /** Enter 提交前的钩子；`event.preventDefault()` 可阻止提交与换行（Svelte 5 的事件类 prop 用小写命名，与 `onsubmit` 一致） */
    onenter?: (event: KeyboardEvent) => void
    popupMode?: PopupMode
    popupScrollBehavior?: PopupScrollBehavior
    /** 提交回调（列表关闭时按 Enter / 调用 snippet 里的 submit） */
    onsubmit?: (parts: Part[]) => void
    /** 内容变化回调 */
    onchange?: (parts: Part[]) => void

    // ── snippet props，作用域与 Vue 版同名 slot 一致（见 packages/vue/src/MentionInput.vue）──
    /** 整个候选列表都自己渲染（需要自己处理 ids / 分页 / 无障碍） */
    list?: Snippet<
      [
        {
          items: MentionItem[]
          activeIndex: number
          select: (item: MentionItem) => void
          loading: boolean
          hasMore: boolean
          loadingMore: boolean
          loadMore: () => void
          ids: MentionCoreIds
        },
      ]
    >
    /** 单个候选项的内容（外层 div 的 class / role / mousedown 仍由本组件负责） */
    item?: Snippet<[{ item: MentionItem; active: boolean; select: () => void }]>
    empty?: Snippet<[{ query: string }]>
    error?: Snippet<[{ error: unknown }]>
    loading?: Snippet
    loadingMore?: Snippet
    /** 编辑器内部右下角的操作区（如发送按钮） */
    innerActions?: Snippet<[ActionSlotProps]>
    /** 编辑器下方的操作栏 */
    actions?: Snippet<[ActionSlotProps]>
    /** 兜底内容，渲染在最下方；参数与 Vue 版默认 slot 一致 */
    children?: Snippet<
      [ActionSlotProps & { focus: () => void; getParts: () => Part[] }]
    >
  }

  let {
    triggers,
    placeholder = '',
    disabled = false,
    maxHeight = '200px',
    submitOnEnter = true,
    onenter,
    popupMode = 'fixed',
    popupScrollBehavior = 'reposition',
    onsubmit,
    onchange,
    list,
    item,
    empty,
    error,
    loading,
    loadingMore,
    innerActions,
    actions,
    children,
  }: MentionInputProps = $props()

  // options 只在初始化时读取一次，后续变化经由 setOptions 同步（triggers 引用变化会关闭列表）
  const mention = untrack(() => createMention({ triggers, popupMode, popupScrollBehavior }))

  $effect(() => {
    mention.setOptions({ triggers, popupMode, popupScrollBehavior })
  })

  let listEl = $state<HTMLElement>()

  // ── 提交 / 内容变化 ──
  function submit() {
    // core 的 isEmpty 把「只有 mention、没有文字」也算作非空
    if (mention.state.isEmpty) return
    const parts = mention.getParts()
    onsubmit?.(parts)
    mention.clear()
  }

  function handleInput() {
    onchange?.(mention.getParts())
  }

  function handleKeydown(event: KeyboardEvent) {
    // 输入法组词中：交给 IME 处理，不提交、不 preventDefault
    if (event.isComposing || event.keyCode === 229) return
    // 列表打开时导航 / 选中 / 关闭全部归 core（它会 preventDefault），这里不插手
    if (mention.state.isOpen) return
    if (event.defaultPrevented) return
    if (event.key !== 'Enter' || event.shiftKey) return

    onenter?.(event)
    if (event.defaultPrevented) return
    if (!submitOnEnter) return

    event.preventDefault()
    submit()
  }

  function selectItem(mentionItem: MentionItem) {
    mention.select(mentionItem)
  }

  // ── 分页：滚动接近底部加载下一页 ──
  const NEAR_BOTTOM_PX = 24
  let rafPending = false

  function requestLoadMore() {
    if (mention.state.hasMore && !mention.state.loadingMore) mention.loadMore()
  }

  function handleListScroll() {
    if (rafPending) return
    rafPending = true
    requestAnimationFrame(() => {
      rafPending = false
      const el = listEl
      if (!el) return
      if (el.scrollHeight - el.scrollTop - el.clientHeight <= NEAR_BOTTOM_PX) requestLoadMore()
    })
  }

  // 首屏 / 追加后如果内容撑不满容器（没有滚动条，scroll 事件永远不触发），主动补下一页
  $effect(() => {
    const { isOpen, hasMore, loading, loadingMore, filteredItems } = mention.state
    if (!listEl || !isOpen || !hasMore || loading || loadingMore) return
    if (filteredItems.length === 0) return
    if (listEl.scrollHeight <= listEl.clientHeight + 1) mention.loadMore()
  })

  // 高亮项滚动到可视区
  $effect(() => {
    void mention.state.activeIndex
    if (!listEl) return
    listEl.querySelector<HTMLElement>('.mentionly-list-item--active')?.scrollIntoView({ block: 'nearest' })
  })

  // ── 弹窗定位：fixed 模式贴编辑器宽度，cursor 模式跟随光标（位置由 core 算好）──
  const dropdownStyle = $derived.by(() => {
    const pos = mention.state.popupPosition
    const base = `position: fixed; top: ${pos.top}px; left: ${pos.left}px; transform: translateY(-100%); margin-top: -4px; z-index: 9999;`
    if (popupMode === 'cursor') {
      return `${base} width: max-content; min-width: 200px; max-width: 320px;`
    }
    return `${base} width: ${pos.width ?? 0}px;`
  })

  // ── 命令式 API（父组件 `bind:this={ref}` 后调用）──
  export function insertMention(payload: InsertMentionPayload, options?: InsertMentionOptions) {
    return mention.insertMention(payload, options)
  }

  export function setContent(parts: Part[]) {
    mention.setContent(parts)
  }

  export function getParts(): Part[] {
    return mention.getParts()
  }

  export function clear() {
    mention.clear()
  }

  export function focus() {
    mention.focus()
  }
</script>

<div class="mentionly-wrapper {disabled ? 'mentionly-wrapper--disabled' : ''}">
  <div class="mentionly-editor-area">
    <!-- core 会在编辑器元素上设置 role="combobox" 与 aria-controls/aria-activedescendant -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="mentionly-editor"
      contenteditable={disabled ? 'false' : 'true'}
      aria-placeholder={placeholder}
      data-placeholder={placeholder}
      style="max-height: {maxHeight}"
      use:mention.mention
      oninput={handleInput}
      onkeydown={handleKeydown}
    ></div>

    {#if innerActions}
      {@render innerActions({ submit, clear, isEmpty: mention.state.isEmpty })}
    {/if}
  </div>

  {#if mention.state.error !== null}
    <div class="mentionly-error" role="alert">
      {#if error}
        {@render error({ error: mention.state.error })}
      {:else}
        Failed to load suggestions.
      {/if}
    </div>
  {/if}

  {#if mention.state.isOpen}
    <div class="mentionly-dropdown" style={dropdownStyle}>
      {#if list}
        {@render list({
          items: mention.state.filteredItems,
          activeIndex: mention.state.activeIndex,
          select: selectItem,
          loading: mention.state.loading,
          hasMore: mention.state.hasMore,
          loadingMore: mention.state.loadingMore,
          loadMore: mention.loadMore,
          ids: mention.ids,
        })}
      {:else}
        <div
          bind:this={listEl}
          id={mention.ids.listbox}
          class="mentionly-list"
          role="listbox"
          aria-busy={mention.state.loading || mention.state.loadingMore}
          onscroll={handleListScroll}
        >
          {#if mention.state.loading}
            {#if loading}
              {@render loading()}
            {:else}
              <div class="mentionly-list-loading">Loading...</div>
            {/if}
          {:else if mention.state.filteredItems.length > 0}
            {#each mention.state.filteredItems as mentionItem, index (mentionItem.id)}
              <!-- 选项由编辑器上的 combobox + aria-activedescendant 驱动，自身不要 tabindex -->
              <!-- svelte-ignore a11y_interactive_supports_focus -->
              <div
                id={mention.ids.option(index)}
                class="mentionly-list-item {index === mention.state.activeIndex
                  ? 'mentionly-list-item--active'
                  : ''}"
                role="option"
                aria-selected={index === mention.state.activeIndex}
                onmousedown={(event) => {
                  event.preventDefault()
                  selectItem(mentionItem)
                }}
              >
                {#if item}
                  {@render item({
                    item: mentionItem,
                    active: index === mention.state.activeIndex,
                    select: () => selectItem(mentionItem),
                  })}
                {:else}
                  <span class="mentionly-list-item-label">{mentionItem.label}</span>
                  {#if mentionItem.desc}
                    <span class="mentionly-list-item-desc">{mentionItem.desc}</span>
                  {/if}
                {/if}
              </div>
            {/each}
            {#if mention.state.loadingMore}
              {#if loadingMore}
                {@render loadingMore()}
              {:else}
                <div class="mentionly-list-more" role="status" aria-live="polite">Loading more...</div>
              {/if}
            {/if}
          {:else}
            {#if empty}
              {@render empty({ query: mention.state.query })}
            {:else}
              <div class="mentionly-list-empty">No results</div>
            {/if}
          {/if}
        </div>
      {/if}
    </div>
  {/if}

  {#if actions}
    {@render actions({ submit, clear, isEmpty: mention.state.isEmpty })}
  {/if}

  {#if children}
    {@render children({ submit, clear, isEmpty: mention.state.isEmpty, focus, getParts })}
  {/if}
</div>

// examples/react/src/MentionInput.tsx
/**
 * 一个「可直接复制到自己项目」的完整 mention 输入框组件（React 版）。
 *
 * 复制方式：把 MentionInput.tsx + MentionInput.css 拷到你的项目，改样式即可
 * （依赖只有 @mentionly/react、react 和这个 CSS 文件）。
 *
 * 三条要点（与 Vue 版一致）：
 * 1. 编辑器是空的 contenteditable <div>，通过 hook 的 `ref` 交给 core。
 *    ⚠ 不要往这个 div 里渲染 React 子节点 —— 内部 DOM（mention span、光标等）由 core 直接管理。
 * 2. 候选列表的 id 必须用 `ids.listbox` / `ids.option(i)`：core 会自动在编辑器上设置
 *    aria-controls / aria-activedescendant 指向它们（并补上 role="combobox"，编辑器自己不要写 role）。
 * 3. ↑ ↓ Enter Tab Esc 的键盘导航全部由 core 处理，示例里不要再实现一遍；这里只补「列表关闭时
 *    Enter 提交」和 onEnter 回调。
 *
 * Vue 插槽在这里对应成 render props：
 *   #inner-actions → renderInnerActions   #actions → renderActions
 *   #item → renderItem                    #list → renderList
 *   #empty → renderEmpty                  #loading → renderLoading
 *   #loading-more → renderLoadingMore     #error → renderError
 *   #default → children（函数形式）
 */
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactNode,
} from 'react'
import { useMention } from '@mentionly/react'
import type {
  InsertMentionOptions,
  InsertMentionPayload,
  MentionCoreIds,
  MentionItem,
  MentionTrigger,
  Part,
  PopupMode,
  PopupScrollBehavior,
} from '@mentionly/react'
import './MentionInput.css'

/** 命令式方法（用 ref 拿到，对应 Vue 的 defineExpose） */
export interface MentionInputHandle {
  insertMention: (payload: InsertMentionPayload, options?: InsertMentionOptions) => boolean
  setContent: (parts: Part[]) => void
  getParts: () => Part[]
  getPlainText: () => string
  clear: () => void
  focus: () => void
  /** core 生成的无障碍 id（自定义列表渲染时需要） */
  ids: MentionCoreIds
}

/** `#inner-actions` / `#actions` 插槽参数 */
export interface MentionActionsSlotProps {
  submit: () => void
  clear: () => void
  isEmpty: boolean
}

/** 默认插槽（Vue `#default`）参数 */
export interface MentionDefaultSlotProps extends MentionActionsSlotProps {
  focus: () => void
  getParts: () => Part[]
}

/** `#item` 插槽参数 */
export interface MentionItemSlotProps {
  item: MentionItem
  active: boolean
  select: () => void
}

/** `#list` 插槽参数 */
export interface MentionListSlotProps {
  items: MentionItem[]
  activeIndex: number
  select: (item: MentionItem) => void
  loading: boolean
  hasMore: boolean
  loadingMore: boolean
  loadMore: () => void
  query: string
  ids: MentionCoreIds
}

export interface MentionInputProps {
  /** 触发器配置。数据变化时请用 useMemo / state 保持稳定引用，否则列表会被重置 */
  triggers: MentionTrigger[]
  placeholder?: string
  disabled?: boolean
  /** 编辑器最大高度（CSS 长度，默认 '200px'） */
  maxHeight?: string
  /** Enter 提交（Shift+Enter 换行）。列表打开时 Enter 始终用于选中候选项 */
  submitOnEnter?: boolean
  /**
   * Enter 按下且列表关闭时先调用（Shift+Enter 不触发）。
   * 调用 `e.preventDefault()` 可阻止提交（例如流式输出时）。
   */
  onEnter?: (e: KeyboardEvent) => void
  /** 弹出列表定位模式 */
  popupMode?: PopupMode
  /** 滚动时弹窗行为 */
  popupScrollBehavior?: PopupScrollBehavior
  /** 提交回调：收到 getParts() 的 Part[] */
  onSubmit?: (parts: Part[]) => void
  /** 内容变化回调 */
  onChange?: (parts: Part[]) => void

  // ── 插槽对应（Vue slot → render prop） ──
  /** Vue `#default`：编辑器下方的兜底插槽 */
  children?: (props: MentionDefaultSlotProps) => ReactNode
  /** Vue `#inner-actions`：编辑器内部操作区 */
  renderInnerActions?: (props: MentionActionsSlotProps) => ReactNode
  /** Vue `#actions`：编辑器下方操作栏 */
  renderActions?: (props: MentionActionsSlotProps) => ReactNode
  /** Vue `#item`：自定义候选项渲染（内容在 .mentionly-list-item 内） */
  renderItem?: (props: MentionItemSlotProps) => ReactNode
  /** Vue `#list`：整块自定义候选列表 */
  renderList?: (props: MentionListSlotProps) => ReactNode
  /** Vue `#empty` */
  renderEmpty?: (props: { query: string }) => ReactNode
  /** Vue `#loading` */
  renderLoading?: () => ReactNode
  /** Vue `#loading-more` */
  renderLoadingMore?: () => ReactNode
  /** Vue `#error` */
  renderError?: (props: { error: unknown }) => ReactNode
}

const NEAR_BOTTOM_PX = 24

/**
 * 默认候选列表（对应 Vue 的 MentionList.vue）。
 * 结构与类名与 Vue 版保持一致，样式在 MentionInput.css 里。
 */
interface DefaultMentionListProps {
  items: MentionItem[]
  activeIndex: number
  query: string
  loading: boolean
  hasMore: boolean
  loadingMore: boolean
  ids: MentionCoreIds
  select: (item: MentionItem) => void
  loadMore: () => void
  renderItem?: (props: MentionItemSlotProps) => ReactNode
  renderEmpty?: (props: { query: string }) => ReactNode
  renderLoading?: () => ReactNode
  renderLoadingMore?: () => ReactNode
}

function DefaultMentionList({
  items,
  activeIndex,
  query,
  loading,
  hasMore,
  loadingMore,
  ids,
  select,
  loadMore,
  renderItem,
  renderEmpty,
  renderLoading,
  renderLoadingMore,
}: DefaultMentionListProps) {
  const listRef = useRef<HTMLDivElement | null>(null)
  const rafRef = useRef<number | null>(null)
  const itemCount = items.length

  const requestLoadMore = useCallback(() => {
    if (hasMore && !loadingMore) loadMore()
  }, [hasMore, loadingMore, loadMore])

  // 选中项始终滚进可视区（对应 Vue MentionList 里的 activeIndex watch）
  useEffect(() => {
    const container = listRef.current
    if (!container) return
    const active = container.querySelector<HTMLElement>('.mentionly-list-item--active')
    active?.scrollIntoView?.({ block: 'nearest' })
  }, [activeIndex])

  // 首屏 / 追加后若内容撑不满容器（无法滚动），主动补下一页直到填满或没有更多
  useEffect(() => {
    const el = listRef.current
    if (!el) return
    if (el.scrollHeight <= el.clientHeight + 1) requestLoadMore()
  }, [itemCount, requestLoadMore])

  const handleScroll = useCallback(() => {
    if (rafRef.current !== null) return
    rafRef.current = window.requestAnimationFrame(() => {
      rafRef.current = null
      const el = listRef.current
      if (!el) return
      if (el.scrollHeight - el.scrollTop - el.clientHeight <= NEAR_BOTTOM_PX) requestLoadMore()
    })
  }, [requestLoadMore])

  useEffect(
    () => () => {
      if (rafRef.current !== null) window.cancelAnimationFrame(rafRef.current)
    },
    [],
  )

  return (
    <div
      ref={listRef}
      id={ids.listbox}
      className="mentionly-list"
      role="listbox"
      aria-busy={loading || loadingMore}
      onScroll={handleScroll}
    >
      {loading ? (
        renderLoading ? (
          renderLoading()
        ) : (
          <div className="mentionly-list-loading">Loading...</div>
        )
      ) : items.length > 0 ? (
        <>
          {items.map((item, index) => {
            const active = index === activeIndex
            return (
              <div
                key={item.id}
                id={ids.option(index)}
                className={`mentionly-list-item${active ? ' mentionly-list-item--active' : ''}`}
                role="option"
                aria-selected={active}
                // mousedown + preventDefault：选中候选项的同时不让编辑器失焦
                onMouseDown={(e) => {
                  e.preventDefault()
                  select(item)
                }}
              >
                {renderItem ? (
                  renderItem({ item, active, select: () => select(item) })
                ) : (
                  <>
                    <span className="mentionly-list-item-label">{item.label}</span>
                    {item.desc ? <span className="mentionly-list-item-desc">{item.desc}</span> : null}
                  </>
                )}
              </div>
            )
          })}
          {loadingMore &&
            (renderLoadingMore ? (
              renderLoadingMore()
            ) : (
              <div className="mentionly-list-more" role="status" aria-live="polite">
                Loading more...
              </div>
            ))}
        </>
      ) : renderEmpty ? (
        renderEmpty({ query })
      ) : (
        <div className="mentionly-list-empty">No results</div>
      )}
    </div>
  )
}

export const MentionInput = forwardRef<MentionInputHandle, MentionInputProps>(function MentionInput(
  {
    triggers,
    placeholder = '',
    disabled = false,
    maxHeight = '200px',
    submitOnEnter = true,
    onEnter,
    popupMode = 'fixed',
    popupScrollBehavior = 'reposition',
    onSubmit,
    onChange,
    children,
    renderInnerActions,
    renderActions,
    renderItem,
    renderList,
    renderEmpty,
    renderLoading,
    renderLoadingMore,
    renderError,
  },
  ref,
) {
  const {
    ref: editorRef,
    state,
    ids,
    core,
    select,
    loadMore,
    getParts,
    getPlainText,
    clear,
    setContent,
    insertMention,
    focus,
  } = useMention({ triggers, popupMode, popupScrollBehavior })

  useImperativeHandle(
    ref,
    () => ({ insertMention, setContent, getParts, getPlainText, clear, focus, ids }),
    [insertMention, setContent, getParts, getPlainText, clear, focus, ids],
  )

  const submit = useCallback(() => {
    // 用 getState() 拿实时状态：React 闭包里的 state 可能停留在上一次渲染
    if (core.getState().isEmpty) return
    onSubmit?.(getParts())
    clear()
  }, [core, getParts, clear, onSubmit])

  const handleKeyDown = useCallback(
    (e: ReactKeyboardEvent<HTMLDivElement>) => {
      const native = e.nativeEvent
      // 输入法组词中：交给 IME，不提交
      if (native.isComposing || native.keyCode === 229) return
      // 列表打开时 core 已处理导航 / Enter / Tab / Esc；它 preventDefault 过就不再重复处理
      // （列表为空时 core 不会 preventDefault，Enter 应继续走提交，与 Vue 版一致）
      // ⚠ 读 nativeEvent.defaultPrevented：core 与 onEnter 都是在原生事件上调 preventDefault，
      //   React 合成事件的 defaultPrevented 不会跟着变。
      if (core.getState().isOpen && native.defaultPrevented) return
      if (e.key !== 'Enter' || e.shiftKey) return

      onEnter?.(native)
      if (native.defaultPrevented) return
      if (!submitOnEnter) return

      e.preventDefault()
      submit()
    },
    [core, onEnter, submitOnEnter, submit],
  )

  const handleInput = useCallback(() => {
    if (onChange) onChange(getParts())
  }, [onChange, getParts])

  const { isOpen, filteredItems, activeIndex, query, loading, loadingMore, hasMore, popupPosition, isEmpty, error } =
    state

  const dropdownStyle = useMemo<CSSProperties>(() => {
    const pos = popupPosition
    if (popupMode === 'cursor') {
      return {
        position: 'fixed',
        top: pos.top,
        left: pos.left,
        transform: 'translateY(-100%)',
        marginTop: -4,
        width: 'max-content',
        minWidth: 200,
        maxWidth: 320,
        zIndex: 9999,
      }
    }
    // fixed 模式：下拉框在编辑器正上方，宽度与编辑器一致
    return {
      position: 'fixed',
      top: pos.top,
      left: pos.left,
      transform: 'translateY(-100%)',
      marginTop: -4,
      width: pos.width ?? 0,
      zIndex: 9999,
    }
  }, [popupPosition, popupMode])

  return (
    <div className={`mentionly-wrapper${disabled ? ' mentionly-wrapper--disabled' : ''}`}>
      <div className="mentionly-editor-area">
        <div
          ref={editorRef}
          className="mentionly-editor"
          contentEditable={!disabled}
          // role="combobox" 与 aria-* 由 core 设置，这里不要写 role
          aria-placeholder={placeholder}
          data-placeholder={placeholder}
          style={{ maxHeight }}
          onKeyDown={handleKeyDown}
          onInput={handleInput}
        />

        {/* 输入框内部操作区 */}
        {renderInnerActions?.({ submit, clear, isEmpty })}
      </div>

      {/* 数据源错误（error 非 null 时显示） */}
      {error !== null && (
        <div className="mentionly-error" role="alert">
          {renderError ? renderError({ error }) : 'Failed to load suggestions.'}
        </div>
      )}

      {/* 候选项下拉列表 */}
      {isOpen && (
        <div className="mentionly-dropdown" style={dropdownStyle}>
          {renderList ? (
            renderList({ items: filteredItems, activeIndex, select, loading, hasMore, loadingMore, loadMore, query, ids })
          ) : (
            <DefaultMentionList
              items={filteredItems}
              activeIndex={activeIndex}
              query={query}
              loading={loading}
              hasMore={hasMore}
              loadingMore={loadingMore}
              ids={ids}
              select={select}
              loadMore={loadMore}
              renderItem={renderItem}
              renderEmpty={renderEmpty}
              renderLoading={renderLoading}
              renderLoadingMore={renderLoadingMore}
            />
          )}
        </div>
      )}

      {/* 操作栏 */}
      {renderActions?.({ submit, clear, isEmpty })}

      {/* 兜底插槽 */}
      {typeof children === 'function' ? children({ submit, clear, isEmpty, focus, getParts }) : null}
    </div>
  )
})
