// examples/svelte/src/MentionInput.svelte
<script lang="ts">
  import { untrack } from 'svelte'
  import {
    createMention,
    type MentionItem,
    type MentionTrigger,
    type Part,
  } from '@mentionly/svelte'

  let {
    triggers,
    placeholder = '输入 @ 提及用户，# 引用话题，Enter 发送',
    onsubmit,
    submitLabel = '发送',
  }: {
    triggers: MentionTrigger[]
    placeholder?: string
    onsubmit?: (parts: Part[]) => void
    submitLabel?: string
  } = $props()

  // options 只在初始化时读取一次（triggers 是稳定引用）
  const mention = untrack(() => createMention({ triggers }))

  // 把 props 变化同步给 core：Svelte 的响应式引用稳定，无需自己比较
  $effect(() => {
    mention.setOptions({ triggers })
  })

  // 高亮项滚动到可视区
  $effect(() => {
    if (!mention.state.isOpen) return
    const option = document.getElementById(mention.ids.option(mention.state.activeIndex))
    option?.scrollIntoView({ block: 'nearest' })
  })

  function handleKeydown(event: KeyboardEvent) {
    // 列表打开时导航 / 选中 / 关闭全部由 core 处理（会 preventDefault）
    if (event.defaultPrevented) return
    if (event.key !== 'Enter' || event.shiftKey) return
    if (mention.state.isOpen) return

    event.preventDefault()
    const parts = mention.getParts()
    if (parts.length === 0) return
    onsubmit?.(parts)
    mention.clear()
  }

  function handleScroll(event: Event) {
    const el = event.currentTarget as HTMLElement
    if (!mention.state.hasMore || mention.state.loadingMore) return
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 24) mention.loadMore()
  }

  function pick(item: MentionItem) {
    mention.select(item)
  }

  const activeTrigger = $derived(
    triggers.find((trigger) => trigger.char === mention.state.activeTrigger),
  )
</script>

<div class="mention-input">
  <!-- core 会在编辑器元素上设置 role="combobox" 与 aria-controls/aria-activedescendant -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="editor"
    contenteditable="true"
    data-placeholder={placeholder}
    use:mention.mention
    onkeydown={handleKeydown}
  ></div>

  <button
    type="button"
    class="submit"
    disabled={mention.state.isEmpty}
    onclick={() => {
      const parts = mention.getParts()
      if (parts.length === 0) return
      onsubmit?.(parts)
      mention.clear()
    }}
  >
    {submitLabel}
  </button>

  {#if mention.state.isOpen}
    <div class="popup">
      <div class="popup-header">
        <span class="trigger">{activeTrigger?.char ?? '@'}</span>
        <span class="query">{mention.state.query || '全部'}</span>
        {#if mention.state.loading}<span class="spinner">加载中…</span>{/if}
      </div>

      {#if mention.state.error}
        <div class="status error">加载失败：{String(mention.state.error)}</div>
      {:else if !mention.state.loading && mention.state.isEmpty}
        <div class="status">没有匹配项</div>
      {/if}

      <ul
        id={mention.ids.listbox}
        class="list"
        role="listbox"
        onscroll={handleScroll}
      >
        {#each mention.state.filteredItems as item, index (item.id)}
          <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_noninteractive_element_interactions -->
          <li
            id={mention.ids.option(index)}
            class="option"
            class:active={index === mention.state.activeIndex}
            role="option"
            aria-selected={index === mention.state.activeIndex}
            onclick={() => pick(item)}
          >
            {#if item.avatar}
              <img class="avatar" src={item.avatar} alt="" />
            {/if}
            <span class="label">{item.label}</span>
            {#if item.description}
              <span class="description">{item.description}</span>
            {/if}
          </li>
        {/each}
      </ul>

      {#if mention.state.loadingMore}
        <div class="status">加载更多…</div>
      {:else if mention.state.hasMore}
        <div class="status">滚动加载更多</div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .mention-input {
    position: relative;
    display: flex;
    align-items: flex-end;
    gap: 8px;
    padding: 10px 12px;
    border: 1px solid var(--border, #d8dee9);
    border-radius: 12px;
    background: var(--surface, #fff);
    transition: border-color 0.15s ease, box-shadow 0.15s ease;
  }

  .mention-input:focus-within {
    border-color: var(--accent, #4f7cff);
    box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent, #4f7cff) 18%, transparent);
  }

  .editor {
    flex: 1;
    min-height: 24px;
    max-height: 160px;
    overflow-y: auto;
    padding: 4px 2px;
    outline: none;
    line-height: 1.5;
    font-size: 14px;
    color: var(--text, #1f2430);
    white-space: pre-wrap;
    word-break: break-word;
  }

  .editor:empty::before {
    content: attr(data-placeholder);
    color: var(--muted, #9aa3b2);
    pointer-events: none;
  }

  .submit {
    flex: none;
    padding: 6px 14px;
    border: none;
    border-radius: 8px;
    background: var(--accent, #4f7cff);
    color: #fff;
    font-size: 13px;
    font-weight: 500;
    cursor: pointer;
    transition: opacity 0.15s ease;
  }

  .submit:disabled {
    opacity: 0.45;
    cursor: not-allowed;
  }

  .popup {
    position: absolute;
    z-index: 20;
    top: calc(100% + 6px);
    left: 0;
    right: 0;
    max-height: 260px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    border: 1px solid var(--border, #d8dee9);
    border-radius: 12px;
    background: var(--surface, #fff);
    box-shadow: 0 12px 32px rgba(15, 23, 42, 0.14);
    animation: pop 0.12s ease-out;
  }

  @keyframes pop {
    from {
      opacity: 0;
      transform: translateY(-4px);
    }
  }

  .popup-header {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    border-bottom: 1px solid var(--border, #eef1f6);
    font-size: 12px;
    color: var(--muted, #9aa3b2);
  }

  .trigger {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 20px;
    border-radius: 6px;
    background: color-mix(in srgb, var(--accent, #4f7cff) 14%, transparent);
    color: var(--accent, #4f7cff);
    font-weight: 600;
  }

  .query {
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .list {
    margin: 0;
    padding: 4px;
    list-style: none;
    overflow-y: auto;
  }

  .option {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 7px 10px;
    border-radius: 8px;
    font-size: 13px;
    color: var(--text, #1f2430);
    cursor: pointer;
  }

  .option.active {
    background: color-mix(in srgb, var(--accent, #4f7cff) 12%, transparent);
  }

  .avatar {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    object-fit: cover;
  }

  .label {
    font-weight: 500;
  }

  .description {
    margin-left: auto;
    color: var(--muted, #9aa3b2);
    font-size: 12px;
  }

  .status {
    padding: 10px 12px;
    font-size: 12px;
    color: var(--muted, #9aa3b2);
  }

  .status.error {
    color: #d64545;
  }

  .spinner {
    color: var(--accent, #4f7cff);
  }
</style>

// packages/vue/src/MentionInput.vue
<script setup lang="ts">
import { reactive, computed } from 'vue'
import type { MentionTrigger, Part, MentionCoreIds, MentionItem, PopupMode, PopupScrollBehavior } from '@mentionly/core'
import { useMention } from './useMention'
import MentionList from './MentionList.vue'

const props = withDefaults(
  defineProps<{
    triggers: MentionTrigger[]
    placeholder?: string
    disabled?: boolean
    maxHeight?: string
    submitOnEnter?: boolean
    onEnter?: (e: KeyboardEvent) => void
    popupMode?: PopupMode
    popupScrollBehavior?: PopupScrollBehavior
    teleport?: boolean
  }>(),
  {
    placeholder: '',
    disabled: false,
    maxHeight: '200px',
    submitOnEnter: true,
    popupMode: 'fixed',
    popupScrollBehavior: 'reposition',
    teleport: true,
  },
)

const emit = defineEmits<{
  submit: [parts: Part[]]
  change: [parts: Part[]]
}>()

defineSlots<{
  list?: (props: {
    items: MentionItem[]
    activeIndex: number
    select: (item: MentionItem) => void
    loading: boolean
    hasMore: boolean
    loadingMore: boolean
    loadMore: () => void
    /** 自定义列表渲染时用它给 listbox / option 连线 a11y id */
    ids: MentionCoreIds
  }) => any
  item?: (props: { item: MentionItem; active: boolean; select: () => void }) => any
  empty?: (props: { query: string }) => any
  error?: (props: { error: unknown }) => any
  loading?: (props: {}) => any
  'loading-more'?: (props: {}) => any
  'inner-actions'?: (props: {
    submit: () => void
    clear: () => void
    isEmpty: boolean
  }) => any
  actions?: (props: {
    submit: () => void
    clear: () => void
    isEmpty: boolean
  }) => any
  default?: (props: {
    submit: () => void
    clear: () => void
    isEmpty: boolean
    focus: () => void
    getParts: () => Part[]
  }) => any
}>()

const {
  editorRef,
  isOpen,
  filteredItems,
  activeIndex,
  query,
  activeTrigger,
  loading,
  error,
  ids,
  popupPosition,
  hasMore,
  loadingMore,
  select,
  insertMention,
  loadMore,
  close,
  getParts,
  getDataParts,
  getPlainText,
  clear,
  setContent,
  focus,
  isEmpty,
  handlers,
} = useMention(reactive({
  get triggers() { return props.triggers },
  get popupMode() { return props.popupMode },
  get popupScrollBehavior() { return props.popupScrollBehavior },
}))

// 包装 handlers，添加 submit 和 change 逻辑
const wrappedHandlers = {
  ...handlers,
  input: () => {
    handlers.input()
    emit('change', getParts())
  },
  keydown: (e: KeyboardEvent) => {
    // 输入法组词中：交给 IME 处理，不提交、不选中列表项、不 preventDefault
    if (e.isComposing || e.keyCode === 229) return
    if (isOpen.value) {
      handlers.keydown(e)
      // 如果事件未被 preventDefault（列表空时 Enter/Tab 不会 prevent），继续处理
      if (e.defaultPrevented) return
    }

    if (e.key === 'Enter' && !e.shiftKey) {
      props.onEnter?.(e)
      if (e.defaultPrevented) return

      // Enter 提交
      if (props.submitOnEnter) {
        e.preventDefault()
        handleSubmit()
        return
      }
    }

    if (!isOpen.value) {
      handlers.keydown(e)
    }
  },
}

function handleSubmit() {
  if (isEmpty.value) return
  const parts = getParts()
  emit('submit', parts)
  clear()
}

const dropdownStyle = computed(() => {
  const pos = popupPosition.value
  if (props.popupMode === 'cursor') {
    return {
      position: 'fixed' as const,
      top: pos.top + 'px',
      left: pos.left + 'px',
      transform: 'translateY(-100%)',
      marginTop: '-4px',
      width: 'max-content',
      minWidth: '200px',
      maxWidth: '320px',
      zIndex: 9999,
    }
  }
  // fixed mode: 下拉框在编辑器正上方，宽度与编辑器一致
  return {
    position: 'fixed' as const,
    top: pos.top + 'px',
    left: pos.left + 'px',
    transform: 'translateY(-100%)',
    marginTop: '-4px',
    width: (pos.width ?? 0) + 'px',
    zIndex: 9999,
  }
})

defineExpose({
  getParts,
  getDataParts,
  getPlainText,
  clear,
  setContent,
  insertMention,
  focus,
  ids,
})
</script>

<template>
  <div class="mentionly-wrapper" :class="{ 'mentionly-wrapper--disabled': disabled }">
    <div class="mentionly-editor-area">
      <div
        ref="editorRef"
        class="mentionly-editor"
        :contenteditable="!disabled"
        :aria-placeholder="placeholder"
        :data-placeholder="placeholder"
        :style="{ maxHeight }"
        v-on="wrappedHandlers"
      />

      <!-- 输入框内部操作区 -->
      <slot name="inner-actions" :submit="handleSubmit" :clear="clear" :is-empty="isEmpty" />
    </div>

    <!-- 数据源错误（error 非 null 时显示），可用 #error 自定义 -->
    <div v-if="error !== null" class="mentionly-error" role="alert">
      <slot name="error" :error="error">Failed to load suggestions.</slot>
    </div>

    <!-- Teleport 下拉列表到 body -->
    <Teleport to="body" :disabled="!teleport">
      <div
        v-if="isOpen"
        class="mentionly-dropdown"
        :style="dropdownStyle"
      >
        <slot
          name="list"
          :items="filteredItems"
          :active-index="activeIndex"
          :select="select"
          :loading="loading"
          :has-more="hasMore"
          :loading-more="loadingMore"
          :load-more="loadMore"
          :ids="ids"
        >
          <MentionList
            :items="filteredItems"
            :active-index="activeIndex"
            :loading="loading"
            :query="query"
            :has-more="hasMore"
            :loading-more="loadingMore"
            :ids="ids"
            @select="select"
            @load-more="loadMore"
          >
            <template v-if="$slots.item" #item="slotProps">
              <slot name="item" v-bind="slotProps" />
            </template>
            <template v-if="$slots.empty" #empty="slotProps">
              <slot name="empty" v-bind="slotProps" />
            </template>
            <template v-if="$slots.loading" #loading>
              <slot name="loading" />
            </template>
            <template v-if="$slots['loading-more']" #loading-more>
              <slot name="loading-more" />
            </template>
          </MentionList>
        </slot>
      </div>
    </Teleport>

    <!-- 操作栏 -->
    <slot name="actions" :submit="handleSubmit" :clear="clear" :is-empty="isEmpty" />

    <!-- 兜底 slot -->
    <slot :submit="handleSubmit" :clear="clear" :is-empty="isEmpty" :focus="focus" :get-parts="getParts" />
  </div>
</template>

<style>
/* ── Editor ── */
.mentionly-wrapper {
  position: relative;
  width: 100%;
}

.mentionly-wrapper--disabled {
  opacity: 0.6;
  pointer-events: none;
}

.mentionly-editor-area {
  position: relative;
}

.mentionly-editor {
  min-height: 40px;
  padding: 8px 12px;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  outline: none;
  overflow-y: auto;
  word-break: break-word;
  white-space: pre-wrap;
  line-height: 1.5;
  font-size: 14px;
  transition: border-color 0.15s;
}

.mentionly-editor:focus {
  border-color: #3b82f6;
  box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.15);
}

.mentionly-editor:empty::before {
  content: attr(data-placeholder);
  color: #9ca3af;
  pointer-events: none;
}

/* ── Mention Span ── */
.mentionly-mention {
  display: inline;
  background-color: #dbeafe;
  color: #1d4ed8;
  border-radius: 4px;
  padding: 1px 4px;
  font-weight: 500;
  user-select: all;
  white-space: nowrap;
}

/* ── Dropdown ── */
.mentionly-dropdown {
  z-index: 9999;
}

.mentionly-list {
  background: #fff;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
  max-height: 200px;
  overflow-y: auto;
  padding: 4px;
  scrollbar-width: thin;
  scrollbar-color: #d1d5db transparent;
}

.mentionly-list::-webkit-scrollbar {
  width: 6px;
}

.mentionly-list::-webkit-scrollbar-track {
  background: transparent;
  margin: 4px 0;
}

.mentionly-list::-webkit-scrollbar-thumb {
  background: #d1d5db;
  border-radius: 3px;
}

.mentionly-list::-webkit-scrollbar-thumb:hover {
  background: #9ca3af;
}

.mentionly-list-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.1s;
}

.mentionly-list-item:hover,
.mentionly-list-item--active {
  background-color: #f3f4f6;
}

.mentionly-list-item-label {
  font-weight: 500;
  color: #111827;
}

.mentionly-list-item-desc {
  color: #6b7280;
  font-size: 12px;
}

.mentionly-list-empty,
.mentionly-list-loading {
  padding: 12px;
  text-align: center;
  color: #9ca3af;
  font-size: 13px;
}

.mentionly-error {
  margin-top: 6px;
  padding: 6px 10px;
  border: 1px solid #fecaca;
  border-radius: 6px;
  background: #fef2f2;
  color: #b91c1c;
  font-size: 12px;
}

.mentionly-list-more {
  padding: 8px;
  text-align: center;
  color: #9ca3af;
  font-size: 12px;
}
</style>
